#ifndef VCVM_ERROR_CODES_HEADER_GUARD
#define VCVM_ERROR_CODES_HEADER_GUARD

/* make this header C++ friendly. */
#ifdef __cplusplus
extern "C" {
#endif  //__cplusplus

#define VCVM_STATUS_SUCCESS 0x0000

#define VCVM_ERROR_BYTECODE_NOT_ENOUGH_BYTES 0x1000
#define VCVM_ERROR_BYTECODE_BAD_MAGIC 0x1001

#define VCVM_ERROR_INTRINSIC_NOT_FOUND 0x2000

#define VCVM_ERROR_VM_BAD_ARITY 0x3001
#define VCVM_ERROR_VM_INVALID_OPCODE 0x3002
#define VCVM_ERROR_VM_HALT 0x3003
#define VCVM_ERROR_VM_STACKOVERFLOW 0x3004
#define VCVM_ERROR_VM_STACKUNDERFLOW 0x3005
#define VCVM_ERROR_VM_BAD_TYPES 0x3006
#define VCVM_ERROR_VM_BAD_CONSTANT_COUNT 0x3007
#define VCVM_ERROR_VM_CANT_COMPARE_DIFFERENT_TYPES 0x3008
#define VCVM_ERROR_VM_UNKNOWN_COMPARE 0x3009
#define VCVM_ERROR_VM_ASSERTION_ERROR 0x300a

#define VCVM_ERROR_BUILDER_BAD_TOTAL_SIZE 0x4001

#define VCVM_ERROR_CANT_ALLOCATE 0xF000
#define VCVM_ERROR_STACK_VALUE_CANT_COPY 0xF001

#ifdef __cplusplus
}
#endif  //__cplusplus

#endif
